spring.application.name=auth
#enabling the H2 console
spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:mem:test_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

#JWT

jwt.secret=rupalchowdhuryrupalchowdhuryrupalchowdhuryrupalchowdhuryrupalchowdhury

jwt.expiration=10

#Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.redoc.enabled=true
springdoc.redoc.path=/docs